Cleanup
RoboJackets/mtrain-firmware pull request #62
Opened 2022-02-19 22:56 UTC by Arvind-Srinivasan

Fixed some install and documentation.

2022-05-12 02:35 UTC, kasohrab requested changes
It's a lot to review but looking through it briefly I have some questions:
Do we need to delete all these c api files? If they work why can't we just keep them, just in case? 
Also are we sure the FatFs stuff doesn't work either?
And this has been tested on a board? If not then it's ok we can just wait until we can do that.

2022-05-12 02:35 UTC, kasohrab commented on tests/cpp/leds.cpp
> -#include "mtrain.hpp"
the header file is still called mtrain.hpp so it doesn't compile on my computer cause of this.

2022-05-12 02:35 UTC, kasohrab commented on external/middleware/FreeRTOS/Source/include/FreeRTOSConfig.h
> +/* #define configMAX_PRIORITIES					( 56 ) */
```suggestion
```
we can delete this right?

2022-05-12 03:23 UTC, Arvind-Srinivasan commented
It's better to encourage a consistent API and language target. We had a lot of issues before where it was incredibly confusing to figure out why the compiler failed to compile some apis or worse yet, why code worked with one API and not the other.

2022-05-12 03:24 UTC, Arvind-Srinivasan commented
The code has been tested by me but it would be good if someone else can revalidate all the tests

2022-05-13 00:58 UTC, kasohrab commented
moving to monorepo so I already included this pr in that merge.

2022-05-13 00:58 UTC, closed without merging